version: '3.7'

services:
  rawbot:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: ${CONTAINER_USER}/${CONTAINER_NAME}-php:7.3.9
    build:
      context: .
      dockerfile: ./php-cli/Dockerfile
      args:
        - BUILD_ENVIRONMENT=${BUILD_ENVIRONMENT}
        - XDEBUG_HOST=${XDEBUG_HOST}
        - XDEBUG_PORT=${XDEBUG_PORT}
        - USER=${USER}
        - GROUP=${GROUP}
        - WORKERS=${WORKERS}
    working_dir: /app
    restart: always
    volumes:
      - ../:/app:delegated
      - ../:/opt/project:delegated
    networks:
      - default_network
    tty: true
    stdin_open: true
    command: ${CMD}
    depends_on:
      - "mysql"
  mysql:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    command:
      --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=localhost
    ports:
      - 3307:3306
    volumes:
      - ../data:/var/lib/mysql:delegated
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
    name: ${CONTAINER_USER}